---
- name: Probar con set_fact
  hosts: ubuntu1

  tasks:
   - name: Crear una variable
     ansible.builtin.set_fact:
      fichero: ejemplo.txt

   - name: Usar la variable en un módulo
     ansible.builtin.file:
      path: /tmp/{{ fichero }}
      state: touch
      group: root
      owner: root
      mode: "755"

   - name: Crear una variable con una expresion
     ansible.builtin.set_fact:
      nombre: "{{ ansible_facts['hostname'] | upper }}"

   - name: Visualizar la variable
     ansible.builtin.debug:
      msg: "El nombre de la máquina en mayúsculas es {{ nombre }}.\n"