---
- name: Prueba con WHEN. Ignorar errores
  hosts: ubuntu1

  tasks:
    - name: Acceder a un firectorio incorrecto
      ansible.builtin.command:
        cmd: ls /temporal
      register: resultado
      ignore_errors: true

    - name: Visualizar Resultado
      ansible.builtin.debug:
        msg: "{{ resultado.stderr }}"
      when: resultado.stderr != ""
